sudo: false
language: node_js
node_js:
  - 10
install:
  - 'npm i'
before_script:
  - npm run build
  - npm run storybook-production &
script:
  - docker run -d -p 4444:4444 -p 5900:5900 selenium/standalone-chrome-debug
  - npm run test
branches:
  only:
    - master
