sudo: false
language: node_js
node_js:
  - 10
install:
  - 'npm i'
before_script:
  - npm run build
  - npm run storybook-production &
script:
  - docker-compose up -d
  - npm run test
branches:
  only:
    - master
