version: '3'
services:
  selenium-chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - '${CHROME_MAIN_PORT:-4444}:4444'
      - '${CHROME_DEBUG_PORT:-5900}:5900'

  selenium-firefox:
    image: selenium/standalone-firefox-debug
    ports:
      - '${FIREFOX_MAIN_PORT:-5555}:4444'
      - '${FIREFOX_DEBUG_PORT:-5901}:5900'
