# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
      - image: selenium/standalone-chrome-debug

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - setup_remote_docker
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run:
          name: Starting the storybook with production mode
          command: npm run storybook-production
          background: true
      
      # run tests!
      - run: docker run --name=selenium -d -p 4444:4444 -p 5900:5900 selenium/standalone-chrome-debug
      - run: npm run test:chrome
      - run: docker rm -f selenium
      - run: docker run --name=selenium -d -p 5555:4444 -p 5901:5900 selenium/standalone-firefox-debug
      - run: npm run test:firefox
      - run: docker rm -f selenium
