# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
      - image: selenium/standalone-chrome-debug
        name: selenium_chrome
      - image: selenium/standalone-firefox-debug
        name: selenium_firefox
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - setup_remote_docker
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run:
          name: Starting the storybook with production mode
          command: npm run storybook-production
          background: true
      - run: WDIO_HOST=selenium_chrome WDIO_PORT=4444 npm run test:chrome
      - run: WDIO_HOST=selenium_firefox WDIO_PORT=4444 npm run test:firefox