name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build
      - run: npm run storybook-production &
      - run: docker-compose up -d
      - run: npm run test:chrome
      - run: npm run test:firefox
