name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run lint
      - run: npm run stylelint
      - run: npm run build
      - run: npm run storybook-production &
      - run: docker run -d -p 4444:4444 -p 5900:5900 selenium/standalone-chrome-debug
      - run: npm run test
